### PR TITLE
Issue 23 fix bugs found during real project integration

### LINKED ISSUE #23: [Bug]Fix bugs found during integrating the module into a real project
**Describe the bug**
No Bug present at the moment, but all bugs found during integration into a  real project shall be logged against this ticket.

### PR DESCRIPTION
**Pull request by artofimagination**
Closes #23

### CODE REVIEW

File: models/asset.go [hunk 1]
```diff
@@ -68,19 +64,19 @@ func (r *Asset) SetImagePath(typeString string) error {
 		return err
 	}
 
-	r.DataMap[typeString] = fmt.Sprintf("%s/%s.jpg", r.DataMap[BaseAssetPath], newID.String())
+	r.DataMap[typeString] = path.Join(r.DataMap[BaseAssetPath].(string), newID.String()+extension)
```
Comment (pongi1987) [inline models/asset.go:67]:
```suggestion
	r.DataMap[typeString] = strings. Join(path.Join(r.DataMap[BaseAssetPath].(string), newID.String(), extension), "") 
```

**Review by pongi1987 — APPROVED** [review]

File: models/asset.go (hunk 1 above)
Comment (artofimagination) [reply models/asset.go]: Okay got the concept. Changed it.
