### PR TITLE
Issue 33 fix third party bugs

### LINKED ISSUE #41: [Task]Adjust the rest responses and tests
**Describe why the task has to be done**
Rest interface will be used to communicate with other services as well besides running tests. Need to adjust to conform this requirement

### PR DESCRIPTION
**Pull request by artofimagination**
Closes #41

### CODE REVIEW

File: restcontrollers/assetController.go [hunk 1]
```diff
@@ -12,214 +11,194 @@ func (c *RESTController) updateUserSettings(w http.ResponseWriter, r *http.Reque
...
 	userData, err := parseUserData(data)
 	if err != nil {
-		w.WriteHeader(http.StatusBadRequest)
-		fmt.Fprint(w, "Failed to get suer")
+		writeError(err.Error(), w, http.StatusBadRequest)
+		return
 	}
 
 	err = c.DBController.UpdateUserSettings(userData)
 	if err == nil {
```
Comment (pongi1987) [inline restcontrollers/assetController.go:25]: Try to use early return instead.
Check for errors, handle errors, and go on with this part.

File: restcontrollers/assetController.go [hunk 2]
```diff
@@ -12,214 +11,194 @@ func (c *RESTController) updateUserSettings(w http.ResponseWriter, r *http.Reque
...
 
 	userData, err := parseUserData(data)
 	if err != nil {
-		w.WriteHeader(http.StatusBadRequest)
-		fmt.Fprint(w, "Failed to get suer")
+		writeError(err.Error(), w, http.StatusBadRequest)
 	}
 
 	err = c.DBController.UpdateUserAssets(userData)
 	if err == nil {
```
Comment (pongi1987) [inline restcontrollers/assetController.go:57]: The same here, first handle err != nil cases

File: restcontrollers/projectController.go [hunk 3]
```diff
@@ -108,195 +102,166 @@ func (c *RESTController) addProject(w http.ResponseWriter, r *http.Request) {
...
-	w.WriteHeader(http.StatusInternalServerError)
-	fmt.Fprint(w, err.Error())
+	writeError(err.Error(), w, http.StatusInternalServerError)
 }
 
 func (c *RESTController) deleteProject(w http.ResponseWriter, r *http.Request) {
 	log.Println("Deleting project")
 	data, err := decodePostData(w, r)
 	if err != nil {
+		writeError(err.Error(), w, http.StatusBadRequest)
```
Comment (pongi1987) [inline restcontrollers/projectController.go:234]: If I were you I think I create a new wrapper around http.ResponseWriter and bind writeError to that new item/struct/interface.
`func (w ResponseWriter) writeError(err error, status int) `

and use it in the following way:
`w.writeError(err.Error(), http.StatusBadRequest)`

**Review by pongraczgabor87 — APPROVED** [review]
